core/urls.py
from django.urls import path

from backend.core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),  # noqa E501
]

core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class Endereco(models.Model):
    endereco = models.CharField(
        'endereço',
        max_length=100,
        null=True,
        blank=True
    )
    complemento = models.CharField(
        'complemento',
        max_length=100,
        null=True,
        blank=True
    )
    bairro = models.CharField(
        'bairro',
        max_length=100,
        null=True,
        blank=True
    )
    cidade = models.CharField('cidade', max_length=100, null=True, blank=True)
    uf = models.CharField(
        'UF',
        max_length=2,
        choices=STATE_CHOICES,
        null=True,
        blank=True
    )
    cep = models.CharField('CEP', max_length=9, null=True, blank=True)

    class Meta:
        abstract = True

core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'
    return render(request, template_name)

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="shortcut icon" href="http://html5-training-in-hyderabad.blogspot.com.br/favicon.ico">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <link rel="shortcut icon" href="https://alpinejs.dev/favicon.png">
    <title>OS</title>

  <!-- Bootstrap core CSS -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"> {% endcomment %}


  <!-- Font-awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Alpine Plugins -->
    <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/mask@3.x.x/dist/cdn.min.js"></script>

  <!-- Alpine Core -->
    <script defer src="//unpkg.com/alpinejs" defer></script>

    {% block css %}
    <link
    rel="stylesheet"
    href="{% static '' %}"
    >
    {% endblock css %}

  </head>

  <body>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          {% include "includes/menu.html" %}

          {% block content %}{% endblock content %}
        </div>
      </div>
    </div>

    {% block js %}{% endblock js %}
  </body>

</html>

core/templates/includes/menu.html
{% load static %}
{% block css %}
  <link
    rel="stylesheet"
    href="{% static '' %}"
  >
{% endblock css %}

<nav>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#bs-example-navbar-collapse-1"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <a
    class="navbar-brand"
    href="{% url 'core:index' %}"
  >Home</a>
  <div
    class="collapse navbar-collapse"
    id="bs-example-navbar-collapse-1"
  >
    <ul>
      <li class="nav-item active">
        <a
          class="nav-link"
          href="{% url 'crm:cliente_list' %}"
        >Clientes <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="#"
        >Serviços</a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="{% url 'servico:ordem_servico_list' %}"
        >Ordens de Serviço</a>
      </li>
    </ul>
  </div>
</nav>

core/templates/includes/pagination.html
{% load static %}
{% block css %}
  <link
    rel="stylesheet"
    href="{% static '' %}"
  >
{% endblock css %}


<!-- pagination.html -->
<div class="intro-y flex flex-wrap sm:flex-row sm:flex-nowrap items-center mt-3">
  <nav class="w-full sm:w-auto sm:mr-auto">
    <ul class="pagination">

      <!-- Início da paginação -->

      <!-- Primeira página -->
      {% if page_obj.number != 1 %}
        <li class="page-item">
          <a class="page-link" href="?page=1&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevrons-left" class="lucide lucide-chevrons-left w-4 h-4" data-lucide="chevrons-left"><polyline points="11 17 6 12 11 7"></polyline><polyline points="18 17 13 12 18 7"></polyline></svg> </a>
        </li>
      {% endif %}

      <!-- Página anterior -->
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevron-left" class="lucide lucide-chevron-left w-4 h-4" data-lucide="chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg> </a>
        </li>
      {% endif %}

      <!-- ... -->
      <!-- {% if page_obj.number != 1 %}
        <li class="page-item"> <a class="page-link" href="#">...</a> </li>
      {% endif %} -->

      <!-- Páginas do meio -->
      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 2 primeiras e 2 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' %}

          <li class="page-item {% if page_obj.number == pg %}active{% endif %}"> <a class="page-link" href="?page={{ pg }}&search={{ request.GET.search }}">{{ pg }}</a> </li>

        {% else %}

          {% if page_obj.number == pg %}
            <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
          {% elif pg > page_obj.number|add:'-3' and pg < page_obj.number|add:'3' %}
            <!-- Mostra 2 páginas antes e 2 páginas depois da atual -->
            <li class="page-item"><a class="page-link" href="?page={{ pg }}&search={{ request.GET.search }}">{{ pg }}</a></li>
          {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
            <li class="page-item"> <a class="page-link" href="#">...</a> </li>
          {% endif %}

        {% endif %}
      {% endfor %}

      <!-- ... -->
      <!-- {% if page_obj.number != page_obj.paginator.num_pages %}
        <li class="page-item"> <a class="page-link" href="#">...</a> </li>
      {% endif %} -->

      <!-- Próxima página -->
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevron-right" class="lucide lucide-chevron-right w-4 h-4" data-lucide="chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg> </a>
        </li>
      {% endif %}

      <!-- Última página -->
      {% if page_obj.number != page_obj.paginator.num_pages %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevrons-right" class="lucide lucide-chevrons-right w-4 h-4" data-lucide="chevrons-right"><polyline points="13 17 18 12 13 7"></polyline><polyline points="6 17 11 12 6 7"></polyline></svg> </a>
        </li>
      {% endif %}
      <!-- Fim da paginação -->

    </ul>
  </nav>
</div>

core/templates/index.html
{% load static %}

{% block css %}
  <link
    rel="stylesheet"
    href="{% static 'css/main.css' %}"
  >
{% endblock css %}

{% block content %}
  <div class="container">
    <div class="content">
    <h2>
      Sistema de Ordens de Serviço
    </h2>
    <p>
      Gerencie suas Ordens de Serviço com facilidade.
    </p>
    <p>
      <a
        href="{% url 'crm:cliente_create' %}"
      >Criar Ordem de Serviço</a>
    </p>
  </div>
  <img src="{% static 'img/order.svg' %}" />
  </div>
{% endblock content %}