crm/urls.py
from django.urls import path

from backend.crm import views as v

app_name = 'crm'


urlpatterns = [
    path('', v.ClienteListView.as_view(), name='cliente_list'),  # noqa E501
    path('create/', v.ClienteCreateView.as_view(), name='cliente_create'),  # noqa E501
    path('<int:pk>/', v.ClienteDetailView.as_view(), name='cliente_detail'),  # noqa E501
    path('<int:pk>/update/', v.ClienteUpdateView.as_view(), name='cliente_update'),  # noqa E501
    # path('<int:pk>/delete/', v.ClienteDeleteView.as_view(), name='cliente_delete'),  # noqa E501
]

crm/models.py
from django.db import models
from django.urls import reverse_lazy

from backend.core.models import Endereco


class Cliente(Endereco):
    razao_social = models.CharField('Razão Social', max_length=120, unique=True)
    cnpj = models.CharField('CNPJ', max_length=14, null=True, blank=True)

    class Meta:
        ordering = ('razao_social',)
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def __str__(self):
        return f'{self.razao_social}'

    def get_absolute_url(self):
        return reverse_lazy('crm:cliente_detail', kwargs={'pk': self.pk})

crm/forms.py
from django import forms

from .models import Cliente


class ClienteForm(forms.ModelForm):
    cnpj = forms.CharField(max_length=18, label='CNPJ')

    class Meta:
        model = Cliente
        fields = ('razao_social', 'cnpj', 'endereco', 'complemento', 'bairro', 'cidade', 'uf', 'cep')

crm/views.py
from django.db.models import Q
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView
)

from .forms import ClienteForm
from .models import Cliente


class ClienteListView(ListView):
    model = Cliente
    paginate_by = 20

    def get_queryset(self):
        qs = self.model.objects.all()
        search = self.request.GET.get('search')
        if search:
            qs = qs.filter(
                Q(razao_social__icontains=search)
                | Q(bairro__icontains=search)
                | Q(cidade__icontains=search)
            )
        return qs


class ClienteDetailView(DetailView):
    model = Cliente


class ClienteCreateView(CreateView):
    model = Cliente
    form_class = ClienteForm


class ClienteUpdateView(UpdateView):
    model = Cliente
    form_class = ClienteForm


# class ClienteDeleteView(DeleteView):
#     model = Cliente
#     success_url = reverse_lazy('crm:cliente_list')

crm/templates/cliente/cliente_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Detalhes do Cliente: {{ object.razao_social }}</h1>

  <a
    href="{% url 'crm:cliente_list' %}"
    class="btn btn-link mb-3"
  >Voltar</a>
  <a
    href="{% url 'crm:cliente_create' %}"
    class="btn btn-primary mb-3"
  >Adicionar</a>

  <div class="row">
    <div class="col-md-12">
      <div class="list-group">
        <a
          href="#"
          class="list-group-item list-group-item-action flex-column align-items-start"
        >
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Razão Social</h5>
          <!-- <small class="text-muted">3 days ago</small> -->
          </div>
          <p class="mb-1">{{ object.razao_social }}</p>
          <small class="text-muted">{{ object.cnpj }}</small>
        </a>
      </div>
    </div>
  </div>
{% endblock content %}

crm/templates/cliente/cliente_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
  <div x-data>
    <h1>Adicionar Cliente</h1>

    <div class="row">
      <div class="cols">
        <form
          action="."
          method="POST"
        >
          {% csrf_token %}

          {% for field in form.visible_fields %}
            <div class="form-group">
              <label for="{{ field.label }}">{{ field.label }}</label>
              {% render_field field class="form-control" %}

              {% if field.errors %}
                {% for error in field.errors %}
                  <p class="text-danger">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </div>
          {% endfor %}

          <button
            type="submit"
            class="btn btn-primary"
          >Salvar</button>

        </form>
      </div>
    </div>
  </div>
{% endblock content %}

crm/templates/cliente/cliente_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Lista de Clientes</h1>

  <a
    href="{% url 'crm:cliente_create' %}"
    class="btn btn-primary"
  >Adicionar</a>

  <form id="searchForm">
    <input
      id="id_search"
      name="search"
      class="form-control"
      type="text"
      placeholder="Busca..."
      autofocus
    />
  </form>

  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <thead>
          <tr>
            <th>Razão Social</th>
            <th>CNPJ</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>
                <a href="{{ object.get_absolute_url }}">{{ object.razao_social }}</a>
              </td>
              <td>{{ object.cnpj }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include "includes/pagination.html" %}
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script>
// Get the input field and form
    var input = document.getElementById("id_search");
    var form = document.getElementById("searchForm");

// Add event listener for keypress
    input.addEventListener("keypress", function(event) {
      if (event.keyCode === 13) {
        event.preventDefault(); // Prevent form submission via Enter key
        form.submit(); // Submit the form
      }
    });
  </script>
{% endblock js %}

crm/templates/crm/cliente_detail.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link
  rel="stylesheet"
  href="{% static '' %}"
>
{% endblock css %}


{% block content %}
  <h1>Detalhes do Cliente: {{ object.razao_social }}</h1>

  <a
    href="{% url 'crm:cliente_list' %}"
    class="btn btn-primary mb-3"
  >Voltar</a>
  <a
    href="{% url 'crm:cliente_create' %}"
    class="btn btn-primary mb-3"
  >Adicionar</a>

  <div class="row">
    <div class="col-md-12">
      <div class="list-group">
        <a
          href="#"
          class="list-group-item list-group-item-action flex-column align-items-start"
        >
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Razão Social</h5>
          <!-- <small class="text-muted">3 days ago</small> -->
          </div>
          <p class="mb-1">{{ object.razao_social }}</p>
          <small class="text-muted">{{ object.cnpj }}</small>
        </a>
      </div>
    </div>
  </div>
{% endblock content %}

crm/templates/crm/cliente_form.html
{% load widget_tweaks %}
{% load static %}

{% block css %}
<link
  rel="stylesheet"
  href="{% static 'css/main.css' %}"
>
{% endblock css %}


{% block content %}
  <div x-data>

    <div class="row">
      <div class="cols">
        <form
          class="form"
          action="."
          method="POST"
        >
        <h1>Adicionar Cliente</h1>
          {% csrf_token %}

          {% for field in form.visible_fields %}
            <div class="form-group">
              <label for="{{ field.label }}">{{ field.label }}</label>
              {% render_field field class="form-control" %}

              {% if field.errors %}
                {% for error in field.errors %}
                  <p class="text-danger">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </div>
          {% endfor %}
          
          <div class="box">

          <button
            type="submit"
            class="btn btn-primary"
          >Salvar</button>

          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

crm/templates/crm/cliente_list.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link
  rel="stylesheet"
  href="{% static '' %}"
>
{% endblock css %}

{% block content %}
  <h1>Lista de Clientes</h1>

  <a
    href="{% url 'crm:cliente_create' %}"
    class="btn btn-primary"
  >Adicionar</a>

  <form id="searchForm">
    <input
      id="id_search"
      name="search"
      class="form-control"
      type="text"
      placeholder="Busca..."
      autofocus
    />
  </form>

  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <thead>
          <tr>
            <th>Razão Social</th>
            <th>CNPJ</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>
                <a href="{{ object.get_absolute_url }}">{{ object.razao_social }}</a>
              </td>
              <td>{{ object.cnpj }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include "includes/pagination.html" %}
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script>
// Get the input field and form
    var input = document.getElementById("id_search");
    var form = document.getElementById("searchForm");

// Add event listener for keypress
    input.addEventListener("keypress", function(event) {
      if (event.keyCode === 13) {
        event.preventDefault(); // Prevent form submission via Enter key
        form.submit(); // Submit the form
      }
    });
  </script>
{% endblock js %}